[project]
name = "pymol"
readme = "README.md"
requires-python = ">=3.9"
dynamic=["version"]
license = {file = "LICENSE"}
description = """
PyMOL is a Python-enhanced molecular graphics tool.
It excels at 3D visualization of proteins, small molecules, density,
surfaces, and trajectories. It also includes molecular editing,
ray tracing, and movies. Open Source PyMOL is free to everyone!
"""
authors = [
  {name = "Schrodinger", email = "pymol-users@lists.sourceforge.net"},
]
dependencies = [
  "numpy>=2.0",
]

[build-system]
build-backend = "backend"
backend-path = ["_custom_build"]
requires = [
  "cmake>=3.13.3",
  "numpy>=2.0",
  "setuptools>=69.2.0",
]

[project.optional-dependencies]
dev = [
  "biopython>=1.80",
  "msgpack==1.0.8",
  "pillow==11.1.0",
  "PySide6==6.8.1",
  "pytest==8.2.2",
  "requests==2.32.3",
]

[project.urls]
Homepage = "https://pymol.org"
Documentation = "https://pymol.org/dokuwiki"
Repository = "https://github.com/schrodinger/pymol-open-source"
"Bug Tracker" = "https://github.com/schrodinger/pymol-open-source/issues"
Changelog = "https://github.com/schrodinger/pymol-open-source/blob/master/ChangeLog"

[project.scripts]
pymol = "pymol:launch"

[tool.setuptools.packages.find]
where = ["modules"]

[tool.setuptools.package-data]
pmg_qt = ["forms/*.ui"]

